### PR TITLE
Facilitate creation of subdirectory

### PR DESCRIPTION
**Pull request by garrettboone**
## Improve Healthcheck syntax

This pull request is a (multiple allowed):

* [x] bug fix
* [ ] change of existing behavior
* [ ] new feature

### What you did
"sudo mkdir /home/www-data/.gnupg" will result in error if www-data directory does not already exist.

### CODE REVIEW

**Comment by pabloelcolombiano** [comment]
@garrettboone usually the gnupg is not created in a non-existing directory and the directory architecture has changed since your PR.

Do you consider this PR as still actual?

**Comment by garrettboone** [comment]
Yes, I think it is still relevant, unless you are saying the display of this line in the Healthcheck will now never occur for other reasons. I looked at is as less of a passbolt thing and more of a Linux command thing. https://linux.die.net/man/1/mkdir with the `-p` flag.

Are you saying this message line as a whole is cruft?

**Comment by pabloelcolombiano** [comment]
No, makes sense. I am merging this. Thanks for the hint!

**Comment by stripthis** [comment]
Merged with v4.0

**Pull request closed without merging**
