### PR TITLE
Fix spelling issue

### PR DESCRIPTION
**Pull request by MMeent**
Passbot -> Passbolt

## Fix spelling issue

This pull request is a (multiple allowed):

* [x] bug fix
* [ ] change of existing behavior
* [ ] new feature

Checklist
* [ ] User stories are present (given, when, then format)
* [x] Unit tests are passing
* [x] Selenium tests are passing
* [x] Check style is not triggering new error or warning

### What you did
I fixed a spelling issue in a use of the name of the project

### CODE REVIEW

**Comment by MMeent** [comment]
I do not know why the build failed, but I doubt this has to do with this one-word fix in the HealthCheckTask.

**Comment by stripthis** [comment]
@MMeent gremlins maybe? ;)

**Comment by noglitchyo** [comment]
Thanks for this pull-request @MMeent . It will merged in the next release.

**Comment by stripthis** [comment]
Fixed with 2.1x

**Pull request closed without merging**
