### PR TITLE
Fix php short tag usage

### PR DESCRIPTION
**Pull request by AnatomicJC**
##IMPORTANT: PLEASE READ

The best way to propose a feature is to open an issue on the community forum and discuss your 
ideas there before implementing them: https://community.passbolt.com/

This is only a issue tracker for issues related to the Passbolt API.
For passbolt docker, browser extension, command line interface, in short any other issues 
please use this [the other relevant repositories](https://github.com/passbolt).

Always follow the contribution guidelines when submitting a pull request.
In particular, make sure existing tests still pass, and add unit and selenium tests for all new behavior. When fixing a bug, 
you may want to add a test to verify the fix.

Please follow the following format:

## Fix php short tag usage
This pull request is a (multiple allowed):

* [ ] bug fix
* [ ] change of existing behavior
* [ ] new feature
* [x] php deprecation

Checklist
* [ ] User stories are present (given, when, then format)
* [ ] Unit tests are passing
* [ ] Selenium tests are passing
* [ ] Check style is not triggering new error or warning

### What you did
While reading the commits history, I saw this commit: https://github.com/passbolt/passbolt_api/commit/7b015b3821d2dcea70356e19f6c1f6b9a04e1f56

PHP Short tags usage is deprecated, that's why I propose this pull request.

Thanks for reading,

### CODE REVIEW

**Comment by AnatomicJC** [comment]
BTW, I think I made a mistake, I asked for merge into master, but I made my commit from `develop` branch. It seems I can't change that...
I signed your CLA License, but it is still in pending status..

**Comment by cedricalfonsi** [comment]
Hello @AnatomicJC,

Looking at the [php documentation ](http://php.net/manual/fr/language.basic-syntax.phptags.php), `the tag <?= is always available regardless of the short_open_tag ini setting`.

Why would you like to replace them with the `<?php echo` version ?

**Comment by AnatomicJC** [comment]
Hi @cedricalfonsi 

My bad, I thought this short tag was deprecated, as for `<?` . It seems it is not...

I'm sorry for this, you can forget this pull request.

**Comment by cedricalfonsi** [comment]
No problem @AnatomicJC, contributions are already appreciated. Thank you

**Pull request closed without merging**
