### PR TITLE
Replace asterisk with double colon for gender-neutral representation in German translation

### PR DESCRIPTION
**Pull request by ravage84**
As a German-speaking user of Passbolt, I propose to replace the use of the asterisk sign ``*`` with the double colon ``:`` for gender-neutral representation in German translation strings **solely to improve the readability**.

There are four popular ways to (more or less) write German with gender-neutrality in mind.

Each with an example:

- Alex hat gerade ihr*sein Konto bei Passwort aktiviert!
- Alex hat gerade ihr/sein Konto bei Passwort aktiviert!
- Alex hat gerade ihr:sein Konto bei Passwort aktiviert!
- Alex hat gerade ihr_sein Konto bei Passwort aktiviert!

Of these, the currently chosen asterisk is evidently the least readable one. It is recommended to use the double colon:

> Der sogenannte Gender:Doppelpunkt ist die jüngste Form der gendergerechten Schreibweise und **gilt als leser:innenfreundlicher als Sternchen oder Unterstrich**. Zudem ist er inklusiver, da er von Sprachausgabeprogrammen für Blinde oder Menschen mit Sehbehinderung am besten wiedergegeben werden kann, indem für den Doppelpunkt eine kurze Sprechpause eingefügt wird.

https://www.uni-rostock.de/storages/uni-rostock/UniHome/Vielfalt/Vielfaltsmanagement/Toolbox/UEbersicht_gendern.docx.pdf

### CODE REVIEW

**Comment by stripthis** [comment]
Hello,

Thank you for your feedback and suggestions!

@ravage84 the translations files are actually generated from the translation platform. To change the translation you will need to create an account and propose changes here: https://passbolt.crowdin.com/
Feel free to get in touch with me if you have any questions or comments.

Cheers,

**Comment by ravage84** [comment]
@stripthis I registered and even contributed some missing German translations to get familiar with the tool.

From what I can see, Crowdin isn't really the place to discuss about improvements.
How do you handle discussions about translations for Passbolt?

I would prefer to have a consent on my idea before I reproduce my work there, especially since it is not as easy as search and replace within Crowdin.

**Comment by pabloelcolombiano** [comment]
As mentioned in your other PR, feel free to update the translation on Crowdin using the : notation.

**Comment by ravage84** [comment]
@stripthis my questions here were not really adressed:

> From what I can see, Crowdin isn't really the place to discuss about improvements.
> How do you handle discussions about translations for Passbolt?

> I would prefer to have a consent on my idea before I reproduce my work there, especially since it is not as easy as search and replace within Crowdin.

**Comment by garrettboone** [comment]
You could use the Community Feedback in the forum and if no one objects, I say just go for it! Your contributions are appreciated, thanks.

**Comment by ravage84** [comment]
@garrettboone fair.

Things like writing styles, which this is, are normally part of the [corporate design](https://en.wikipedia.org/wiki/Brand), which is part of the [corporate identity](https://en.wikipedia.org/wiki/Corporate_identity).

That is why I expected to get some official feedback from the folks of Passbolt itself.

**Comment by ravage84** [comment]
[Community forum post](https://community.passbolt.com/t/replace-asterisk-with-double-colon-for-gender-neutral-representation-in-german-translation/7555)

**Pull request closed without merging**
